spring:
  profiles:
    active:
      - local
  datasource:
    url: jdbc:mysql://10.161.64.68:13306?useUnicode=true&characterEncoding=UTF-8&useSSL=true&verifyServerCertificate=false
    username: tc_rds
    password: rds!#%135
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

server:
  port: 8080