spring:
  profiles:
    active:
      - local
  datasource:
    url: jdbc:mysql://sandbox-pg-db.ay1.krane.9rum.cc:3306/reseller_pg?cacheServerConfiguration=true&zeroDateTimeBehavior=convertToNull&autoReconnect=false
    username: resellerpg
    password: resellerpg
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: true

logging:
  level:
    org:
      hibernate:
        SQL:
          debug
        type:
          descriptor:
            sql:
              BasicBinder: debug
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG


server:
  port: 8080